import Joi from "joi";
import { idParamSchema, paginationQuerySchema } from "./commonSchemas.js";

export const postIdParamForCommentsSchema = Joi.object({
  postId: Joi.number().integer().positive().required().messages({
    "number.base": "Post ID must be a number",
    "number.integer": "Post ID must be an integer",
    "number.positive": "Post ID must be a positive number",
    "any.required": "Post ID is required",
  }),
});

const basePaginationQuerySchema = paginationQuerySchema({
  defaultLimit: 10,
  maxLimit: 100,
}).keys({
  search: Joi.string().optional().messages({
    "string.base": "Search must be a string",
  }),
  userId: Joi.number().integer().positive().optional().messages({
    "number.base": "User ID must be a number",
    "number.integer": "User ID must be an integer",
    "number.positive": "User ID must be a positive number",
  }),
  status: Joi.string()
    .valid("draft", "published")
    .optional()
    .messages({
      "any.only": "Status must be either 'draft' or 'published'",
    }),
});

export const createPostSchema = Joi.object({
  title: Joi.string()
    .trim()
    .min(1)
    .max(200)
    .pattern(/^[^<>]*$/)
    .required()
    .messages({
    "string.min": "Title must not be empty",
    "string.max": "Title must not exceed 200 characters",
      "string.pattern.base": "Title contains invalid characters",
    "any.required": "Title is required",
  }),
  body: Joi.string()
    .trim()
    .min(1)
    .max(5000)
    // Disallow angle brackets to reduce XSS risk in body content
    .pattern(/^[^<>]*$/)
    .required()
    .messages({
    "string.min": "Body must not be empty",
      "string.max": "Body must not exceed 5000 characters",
      "string.pattern.base": "Body contains invalid characters",
    "any.required": "Body is required",
  }),
  status: Joi.string().valid("draft", "published").optional().default("draft").messages({
    "any.only": "Status must be either 'draft' or 'published'",
  }),
  // Image is handled by multer middleware (req.file), not validated here
  // image: removed - handled by multer
  // imagePublicId: removed - generated by backend after upload
});

export const updatePostSchema = Joi.object({
  title: Joi.string()
    .trim()
    .min(1)
    .max(200)
    .pattern(/^[^<>]*$/)
    .optional()
    .messages({
    "string.min": "Title must not be empty",
    "string.max": "Title must not exceed 200 characters",
      "string.pattern.base": "Title contains invalid characters",
  }),
  body: Joi.string()
    .trim()
    .min(1)
    .max(5000)
    // Disallow angle brackets to reduce XSS risk in body content
    .pattern(/^[^<>]*$/)
    .optional()
    .messages({
    "string.min": "Body must not be empty",
      "string.max": "Body must not exceed 5000 characters",
      "string.pattern.base": "Body contains invalid characters",
  }),
  status: Joi.string().valid("draft", "published").optional().messages({
    "any.only": "Status must be either 'draft' or 'published'",
  }),
  // Image removal: if image field is explicitly set to empty string or null
  image: Joi.string().optional().allow("", null),
  // Image file is handled by multer middleware (req.file), not validated here
}).min(1).messages({
  "object.min": "At least one field must be provided to update",
});

export const listPostsQuerySchema = basePaginationQuerySchema;

export const postIdParamSchema = idParamSchema("Post ID");


