import Joi, { ObjectSchema } from "joi";
import { idParamSchema, paginationQuerySchema } from "./commonSchemas.js";
import type {
  CreatePostInput,
  UpdatePostInput,
  ListPostsQuery,
} from "../interfaces/postInterface.js";

/**
 * Post ID parameter schema for comments endpoint
 * Validates postId parameter in route
 */
export const postIdParamForCommentsSchema: ObjectSchema<{ postId: number }> =
  Joi.object({
    postId: Joi.number().integer().positive().required().messages({
      "number.base": "Post ID must be a number",
      "number.integer": "Post ID must be an integer",
      "number.positive": "Post ID must be a positive number",
      "any.required": "Post ID is required",
    }),
  });

/**
 * Base pagination query schema with post-specific filters
 * Extends common pagination schema with search, userId, and status filters
 */
const basePaginationQuerySchema = paginationQuerySchema({
  defaultLimit: 10,
  maxLimit: 100,
}).keys({
  search: Joi.string().optional().messages({
    "string.base": "Search must be a string",
  }),
  userId: Joi.number().integer().positive().optional().messages({
    "number.base": "User ID must be a number",
    "number.integer": "User ID must be an integer",
    "number.positive": "User ID must be a positive number",
  }),
  status: Joi.string()
    .valid("draft", "published")
    .optional()
    .messages({
      "any.only": "Status must be either 'draft' or 'published'",
    }),
} as any);

/**
 * Create post schema
 * Validates data for creating a new post
 */
export const createPostSchema: ObjectSchema<CreatePostInput> = Joi.object({
  title: Joi.string()
    .trim()
    .min(1)
    .max(200)
    .pattern(/^[^<>]*$/)
    .required()
    .messages({
      "string.min": "Title must not be empty",
      "string.max": "Title must not exceed 200 characters",
      "string.pattern.base": "Title contains invalid characters",
      "any.required": "Title is required",
    }),
  body: Joi.string()
    .trim()
    .min(1)
    .max(5000)
    // Disallow angle brackets to reduce XSS risk in body content
    .pattern(/^[^<>]*$/)
    .required()
    .messages({
      "string.min": "Body must not be empty",
      "string.max": "Body must not exceed 5000 characters",
      "string.pattern.base": "Body contains invalid characters",
      "any.required": "Body is required",
    }),
  status: Joi.string()
    .valid("draft", "published")
    .optional()
    .default("draft")
    .messages({
      "any.only": "Status must be either 'draft' or 'published'",
    }),
  // Image is handled by multer middleware (req.file), not validated here
  // image: removed - handled by multer
  // imagePublicId: removed - generated by backend after upload
});

/**
 * Update post schema
 * Validates data for updating an existing post
 * All fields are optional (partial update)
 */
export const updatePostSchema: ObjectSchema<UpdatePostInput> = Joi.object({
  title: Joi.string()
    .trim()
    .min(1)
    .max(200)
    .pattern(/^[^<>]*$/)
    .optional()
    .messages({
      "string.min": "Title must not be empty",
      "string.max": "Title must not exceed 200 characters",
      "string.pattern.base": "Title contains invalid characters",
    }),
  body: Joi.string()
    .trim()
    .min(1)
    .max(5000)
    // Disallow angle brackets to reduce XSS risk in body content
    .pattern(/^[^<>]*$/)
    .optional()
    .messages({
      "string.min": "Body must not be empty",
      "string.max": "Body must not exceed 5000 characters",
      "string.pattern.base": "Body contains invalid characters",
    }),
  status: Joi.string()
    .valid("draft", "published")
    .optional()
    .messages({
      "any.only": "Status must be either 'draft' or 'published'",
    }),
  // Image removal: if image field is explicitly set to empty string or null
  image: Joi.string().optional().allow("", null),
  // Image file is handled by multer middleware (req.file), not validated here
})
  .min(1)
  .messages({
    "object.min": "At least one field must be provided to update",
  });

/**
 * List posts query schema
 * Validates query parameters for listing posts
 */
export const listPostsQuerySchema: ObjectSchema<ListPostsQuery> =
  basePaginationQuerySchema;

/**
 * Post ID parameter schema
 * Validates post ID parameter in route
 */
export const postIdParamSchema = idParamSchema("Post ID");

// Re-export interfaces for backward compatibility
export type {
  CreatePostInput,
  UpdatePostInput,
  ListPostsQuery,
};

